[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "20"

[build]
  publish = "docs/build"
  command = "pnpm run build && pnpm run docs:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
