[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "20"

[build]
  publish = "docs/build"
  command = "npx pnpm i --store=node_modules/.pnpm-store && pnpm run build && npx pnpm run docs:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
